language: php

php:
    - 7.1
    - 7.2

before_install:
    - composer self-update

install:
    - composer install --no-interaction --prefer-source

script:
    - composer coding-standard
    - composer phpstan-analysis
    - sh tests/nette-tester/tests

services:
    - redis-server
