version: "3"
services:
    server:
        container_name: server
        working_dir: /var/www/html
        ports:
            - '80:80'
        build: .
        volumes:
            - .:/var/www/html
            - ./tmp:/tmp
